Get-ChildItem c:\temp

Get-Item c:\temp\asdf.txt

Get-Content c:\temp\asdf.txt

Remove-Item c:\temp\asdf.txt

Get-ChildItem | Where-Object { $_.Extension -eq '.txt' }

# list all known aliases to find what is missing
Get-Command ForEach-Object
Get-Command Where-Object
Get-Command Set-Location
Get-Command Set-Location
Get-Command Clear-Content
Get-Command Clear-Host
Get-Command Clear-History
Get-Command Clear-Item
Get-Command Clear-ItemProperty
Get-Command Clear-Host
Get-Command Clear-Variable
Get-Command Connect-PSSession
Get-Command Copy-Item
Get-Command Copy-Item
Get-Command Convert-Path
Get-Command Disable-PSBreakpoint
Get-Command Remove-Item
Get-Command Get-ChildItem
Get-Command Disconnect-PSSession
Get-Command Enable-PSBreakpoint
Get-Command Write-Output
Get-Command Export-Alias
Get-Command Export-Csv
Get-Command Remove-Item
Get-Command Enter-PSSession
Get-Command Exit-PSSession
Get-Command Format-Custom
Get-Command Format-Hex
Get-Command Format-List
Get-Command Format-Table
Get-Command Format-Wide
Get-Command Get-Alias
Get-Command Get-PSBreakpoint
Get-Command Get-Content
Get-Command Get-ChildItem
Get-Command Get-Command
Get-Command Get-PSCallStack
Get-Command Get-PSDrive
Get-Command Get-History
Get-Command Get-Item
Get-Command Get-Job
Get-Command Get-Location
Get-Command Get-Member
Get-Command Get-Module
Get-Command Get-ItemProperty
Get-Command Get-Process
Get-Command Get-ItemPropertyValue
Get-Command Group-Object
Get-Command Get-PSSession
Get-Command Get-TimeZone
Get-Command Get-Unique
Get-Command Get-Variable
Get-Command Get-History
Get-Command Get-History
Get-Command Invoke-Command
Get-Command Invoke-Expression
Get-Command Invoke-History
Get-Command Invoke-Item
Get-Command Import-Alias
Get-Command Import-Csv
Get-Command Import-Module
Get-Command Invoke-RestMethod
Get-Command Invoke-WebRequest
Get-Command Stop-Process
Get-Command mkdir
Get-Command Measure-Object
Get-Command Move-Item
Get-Command Move-Item
Get-Command Move-ItemProperty
Get-Command New-Alias
Get-Command New-PSDrive
Get-Command New-Item
Get-Command New-Module
Get-Command New-PSSession
Get-Command New-Variable
Get-Command Out-Host
Get-Command Pop-Location
Get-Command Push-Location
Get-Command Get-Location
Get-Command Invoke-History
Get-Command Remove-PSBreakpoint
Get-Command Receive-Job
Get-Command Receive-PSSession
Get-Command Remove-Item
Get-Command Remove-PSDrive
Get-Command Rename-Item
Get-Command Remove-Item
Get-Command Remove-Job
Get-Command Remove-Module
Get-Command Rename-Item
Get-Command Rename-ItemProperty
Get-Command Remove-ItemProperty
Get-Command Remove-PSSession
Get-Command Remove-Variable
Get-Command Resolve-Path
Get-Command Start-Job
Get-Command Set-Alias
Get-Command Start-Process
Get-Command Set-PSBreakpoint
Get-Command Set-Content
Get-Command Select-Object
Get-Command Set-Variable
Get-Command Set-Item
Get-Command Set-Location
Get-Command Select-String
Get-Command Set-ItemProperty
Get-Command Stop-Job
Get-Command Stop-Process
Get-Command Set-Variable
Get-Command Get-Content
Get-Command Where-Object
Get-Command Wait-Job
