dir c:\temp

gi c:\temp\asdf.txt

type c:\temp\asdf.txt

del c:\temp\asdf.txt

Get-ChildItem | where { $_.Extension -eq '.txt' }

# list all known aliases to find what is missing
Get-Command %
Get-Command ?
Get-Command cd
Get-Command chdir
Get-Command clc
Get-Command clear
Get-Command clhy
Get-Command cli
Get-Command clp
Get-Command cls
Get-Command clv
Get-Command cnsn
Get-Command copy
Get-Command cpi
Get-Command cvpa
Get-Command dbp
Get-Command del
Get-Command dir
Get-Command dnsn
Get-Command ebp
Get-Command echo
Get-Command epal
Get-Command epcsv
Get-Command erase
Get-Command etsn
Get-Command exsn
Get-Command fc
Get-Command fhx
Get-Command fl
Get-Command ft
Get-Command fw
Get-Command gal
Get-Command gbp
Get-Command gc
Get-Command gci
Get-Command gcm
Get-Command gcs
Get-Command gdr
Get-Command ghy
Get-Command gi
Get-Command gjb
Get-Command gl
Get-Command gm
Get-Command gmo
Get-Command gp
Get-Command gps
Get-Command gpv
Get-Command group
Get-Command gsn
Get-Command gtz
Get-Command gu
Get-Command gv
Get-Command h
Get-Command history
Get-Command icm
Get-Command iex
Get-Command ihy
Get-Command ii
Get-Command ipal
Get-Command ipcsv
Get-Command ipmo
Get-Command irm
Get-Command iwr
Get-Command kill
Get-Command md
Get-Command measure
Get-Command mi
Get-Command move
Get-Command mp
Get-Command nal
Get-Command ndr
Get-Command ni
Get-Command nmo
Get-Command nsn
Get-Command nv
Get-Command oh
Get-Command popd
Get-Command pushd
Get-Command pwd
Get-Command r
Get-Command rbp
Get-Command rcjb
Get-Command rcsn
Get-Command rd
Get-Command rdr
Get-Command ren
Get-Command ri
Get-Command rjb
Get-Command rmo
Get-Command rni
Get-Command rnp
Get-Command rp
Get-Command rsn
Get-Command rv
Get-Command rvpa
Get-Command sajb
Get-Command sal
Get-Command saps
Get-Command sbp
Get-Command sc
Get-Command select
Get-Command set
Get-Command si
Get-Command sl
Get-Command sls
Get-Command sp
Get-Command spjb
Get-Command spps
Get-Command sv
Get-Command type
Get-Command where
Get-Command wjb
